Alevin: Fixing following crash:
2019-09-10 13:41:57,359;44;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: ReclamationAgreementProject needs to implement IAuditableEntity
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject, String message) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\LtInfo.Common\DesignByContract\Check.cs:line 123
   at ProjectFirmaModels.Models.AuditLog.GetIAuditableEntityFromEntity(Object entity, String tableName) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\AuditLog.cs:line 368
   at ProjectFirmaModels.Models.AuditLog.CreateAuditLogEntryForDeleted(ObjectContext objectContext, DbEntityEntry dbEntry, String tableName, Person person, DateTime changeDate, AuditLogEventType auditLogEventType, Int32 tenantID) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\AuditLog.cs:line 153
   at ProjectFirmaModels.Models.AuditLog.GetAuditLogRecordsForModifiedOrDeleted(DbEntityEntry dbEntry, Person person, ObjectContext objectContext, Int32 tenantID) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\AuditLog.cs:line 95
   at ProjectFirmaModels.Models.DatabaseEntities.SaveChangesImpl(Person person, Tenant tenant, TransactionScope scope) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\DatabaseEntities.cs:line 76
   at ProjectFirmaModels.Models.DatabaseEntities.SaveChanges(Person userPerson) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\DatabaseEntities.cs:line 42
   at ProjectFirmaModels.Models.DatabaseEntities.SaveChanges() in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\DatabaseEntities.cs:line 48
   at ProjectFirma.Web.Common.SitkaController.OnActionExecuted(ActionExecutedContext filterContext) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirma.Web\Common\SitkaController.cs:line 158
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Devin Mounts
LogonName: devin.mounts@sitkatech.com
PersonID: 5636
Organization: Sitka Technology Group

IP Address: 192.168.10.192
Hostname: devrig09.sitka.local
Whois Info:
            NetRange:       192.168.0.0 - 192.168.255.255
            CIDR:           192.168.0.0/16
            NetName:        PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
            NetHandle:      NET-192-168-0-0-1
            Parent:         NET192 (NET-192-0-0-0-0)
            NetType:        IANA Special Use
            OriginAS:
            Organization:   Internet Assigned Numbers Authority (IANA)
            RegDate:        1994-03-15
            Updated:        2013-08-30
            Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
            Comment:
            Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers
            Comment:
            Comment:        These addresses were assigned by the IETF, the organization that develops Internet protocols, in the Best Current Practice document, RFC 1918 which can be found at:
            Comment:        http://datatracker.ietf.org/doc/rfc1918
            Ref:            https://rdap.arin.net/registry/ip/192.168.0.0
            OrgName:        Internet Assigned Numbers Authority
            OrgId:          IANA
            Address:        12025 Waterfront Drive
            Address:        Suite 300
            City:           Los Angeles
            StateProv:      CA
            PostalCode:     90292
            Country:        US
            RegDate:
            Updated:        2012-08-31
            Ref:            https://rdap.arin.net/registry/entity/IANA
            OrgTechHandle: IANA-IP-ARIN
            OrgTechName:   ICANN
            OrgTechPhone:  +1-310-301-5820
            OrgTechEmail:  abuse@iana.org
            OrgTechRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN
            OrgAbuseHandle: IANA-IP-ARIN
            OrgAbuseName:   ICANN
            OrgAbusePhone:  +1-310-301-5820
            OrgAbuseEmail:  abuse@iana.org
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN

URL: https://bor.qa.projectfirma.com/Project/DeleteProject/13626

Http Request:
POST /Project/DeleteProject/13626 HTTP/1.1
Connection: close
Content-Length: 0
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.258569825.1553556593; _gid=GA1.2.2018307155.1568044347; ASP.NET_SessionId=zlbnceaiff4c1qz1v0hwgh02; grid_ck_dhtmlcostAuthorityAgreementListGridfilterVisible=0; grid_ck_dhtmlagreementProjectListGridfilterVisible=0; grid_ck_dhtmlproposalsGridfilterVisible=0; grid_ck_dhtmlprojectCalendarYearExpendituresForOrganizationGridfilterVisible=0; grid_ck_dhtmlprojectOrganizationsFromOrganizationGridfilterVisible=0; grid_ck_dhtmlcostAuthorityProjectListGridfilterVisible=0; BureauOfReclamation_Qa=chunks:2; BureauOfReclamation_QaC1=FGNGCRg3dzuVl_jCOzMxyGyd81keMfnf8UspEfk461E9H0wgspRD-QIgHvAYRa2GCu_8hfak1RJ2qSuuIbXiX52m1020lYm8XgPTGtvWdi8Q5y0LbCGipdfq-DLmsoX68_iX3jDyFAx6Y8P21GX1jsSoIvDN6DGfwcX13q2lspadJpguW0hR3H91oKJ8O8edVFvBfIIOrPmre1LD-Bh5tgzAVFLSGnrfsmVy1TgX-cQ6gL93JZLpxphrVswfka7_B51aqzqh1qL4q9BXh1typI9tlfsyCkd76uRTrcaRESfL4rDmpmiY3PwgsPSsAAcSATE1P9zUwFqyYG1oYrtwMzq1fGytbyiaGoer1NaqOdH4RFrZ6zFZgXZNmZ2IFIpUZw8wUpNPaxiLrDxC9ktFPymQqTrN8EcyYw-uk0SjNAUWKsRnZepJZ9KlqSPL3zMfU8JSANpduRPJ1Ozz6djzVbrb-ZunR0lYZBq7uijeKwhiyH1-Th81ADe2bUCyHovu4Ys4_s1vt1oQyOb2IWQRAkxB2hIuSSCgDqlWT5s2jiAuaLsf00UG3aAiyOPomDSHd9wDEBMpw7Xq_1XGIJ_8yaZtL8pI0N8jiIPC9gvb4dy-yBfD81NHBkVz3x9PVmItOlzqRLtOngT-buhNRbw2t91DsS0GUq8nHhUNuohKGMAiZa2MLxtAIl9zu2sYRm8go0Sn0MezJnjVxT9Cee01SkSlsuMsx14LrRMmyzupor4Vs0ccNQv25egpNBIp3gBer7i7ZaxKrvwgifPP1Xui1dbNnrMua3V9I_kafHPAsPH-UY626uZsZENd8c9I7V6Prh_js93p68_JlLdUyYtrRltJxx_b-46RdXg1iWVyOx3iiZj6yIx1iQvrTHbl5xz6f2B_PA7WVpeddZAH3dRuzo_RXrvqIU_aUZu8OfEmPYscHmQwucb_hhAcsgDUIVW0gGH60feF4-JQ_nfAtcXy-PcQkwA6z1ORH1UKoW_x5fmdC9r4YcEORYKflWrrPkfICI7EnU7tSwldjH0_TYgWM74D4lXuNfrRTEg8oLMEg2yut57Dz8bmwOMLqoaXwe5XDeRqWBw__IAaDXYCc7MAfylzT48ppjDnd56FabRkd5x6F7IIcrPDet5z3Bbqd7F3LvByVbQ7OLeugu8Qk3ypC-n7XaBGCisUmBsxnOL_NRgpIXBllaNda99pZ5SDJR24934Jj8DopnD5nV6Fp_sEWwc5IdhPDe7fZmqB-WuHJqTBl2N-46eqsdqj4v3i-Rh80ZqJdoWQcKGGkbFgChUVNMgXBhbMU8WS536Lf60bQlqbmAQNRaXsUP6j14BcZ_povKrvkHu6BQ4rLQ20wVc_AHJ7mvROovRDv9CnQ_KettE2NQlcqLh5ed7fw-lqG9q5fmsJK7SxQWr_maZwyo3KdYvGSoJfz9_iAPwqacdl-HwIdGxlg90RIIhxpc5uQMtepxAtF4QeQjQ2f0isL4eSeEInWbWsmWidRfY7doPj2eytJ-AzEt2ynGIrfkFPFbZp8IhHzHPJgXlFlDBRBN1SZ7j7e_kS41DOljW4aSz3ds6dFy-LBYQ7HpTegyCLOrz387Q7uA7DtNttwwN7Je_3oX_JTouPKIG_TbgjR_NUR4dgLLLl9n6fRrQcE4vRGk4lYyz5-hFKHkwxa2JLRooindUiVpasjpKRlXu5Uw9Nn-WCjXbHXiaUkav1LROBDr5dX9ypaCCxkNh6srAbYCVApPd7hFB7HMhimBNC__enJr4-BK4mbBGh782moC5N4OYQzFJAP7JIZj-0TMO1g8Jq6J-jZU5cGNPqscf8KUUIXWvGKQ_5Az42jpVYJpkoKDWyO4GwH2vA1DTge1exP8XB3CGJDF_10aBKzw7aVmW4JfFgQ8vRE_N08miDsgSgEelAcdfsnY6CwVg2nPq7wHuwYaqwPyqVkkZlfx4eNj6KzXZNJM0SS8dkSOzzvi8Th8xfxeT848NpQwMvLRxI3APws8gL2C6n5XXbeYgMeHmxf5X9RaaWEDP4hkl3JI8nNOza811iODsZjk0z3VeBOUuXgcGrkcuqmbcziIRBt90tfiT8pGw9Pr4WFd2TfvrGlJOa7SJKf1cW5zTjwdyRJzCb97Ft4xdROsXz4nfQYpCg2664QkdBvslLR0N62Q4P_B1hCGW4TQOjkxpoeEfzZfxEkyysOEtgND1vz6jVyUPYX9QhJfVemQ5KnhKmJ2LQ_lLvfYuPFZn-FTmSkHXV26U6vp9NeitsGlK-sSrA3-56vPWvCnxhHTNS2sJgz1yDWzd8G4mzpsTV9A293z3SYEexTFKwdaHLYw-rXhcCq1Ac3pmRav8Hq0kOKVLykiQszyjPqaaicm_Fr87UI3XoI3VFZ6XY8bNWEKo4o3EOwcjrpL1Za6N5zwYu6EtGKgvxtq5bDM8H5WYVphx6J-POL8ysQax1q45m8wFGePYJVubfQI_0ncYk0PmPrwUTxBBePFk3jv-6wAWaKdlUC8d-V48OjtY0K6Aeq9jWffhOmuAHrx3uj_ty_CPjWEA1moVAe1y27vYcsmMsj5EtbQDQ99--SzKtskqQufiORZMZyDP37bUQOuWVzOdUbPP6n8ukVCZe6UTLepSRwL3xNmVaXwJb2q7a2aVzRUpmJdPaR6IRiQX1Ee-CQjOBso5F2XTX_GVEMrI17MlihGT9lZQrSEW8IieJrs_xGb4orsu-yX_cvoPF4MeJP1XDF1UhlCxpXYzqtA4f4b8Xs-Zt1nFbOAVAY0tFDral7qWuNFXvrbsGUoI7PgemjbZp-KFtAKaujHGdlTHP2mdJqF7igOHTrOf2rGEx2j5u6H1bdVsyl29n_c-2fQwwL6pnWdHQ82g3vIAlVOwKB7GG4J2QvAna_ptSnvwlHhnYXnfCzYx4JCSIhhD81DY5fjUoJhUMsuhgdi0k6ErDfADRF1-i2Lfwxr_e_dkl6lEkXRstdgYNIACm5xbdis11qr4uJ_DxiJleaABwbrpyN7woFybRf2gVhgDedUcA-2VEtD6l3Pa_J1zKD0--x9qCT2i91P_NXHKASbHo9i4ZpJU2OCTX9w8oA4dD6AcKhU7oa0NM8vF4FgpRhvrn9aRngvebwwj4cB3ke2JdT1ff2uADy7KvsUSVGsPBsFrBDPpURaLJfdOLtwZmY0C0ZsXkh--zzlanJxdo1KwbpDTolA-_mq9hKUzsXbAUOWfjFK20KLP5xWXKflPF4t-zy3ni9XEAto7jEIMxpVM7hoqS_KvmLDUuQTSuvpfleIIicoqjEi0y2JMXynCkcixOOvRp9WieG-ma1TJIjcBl4zUAGSVc0t9GpdytH8RX85zSMctGtEMa4aFk1lMvEhrAtS0zL-sQ2s7HTXYL6uJRuSE6c4YDnJu1vInAgzeXNIyMYuJ90wk5BHrfiFwfKXyVVL7s3orcluMEgBmR0VFe8cG4miBohIbbxMWNAq82fxgvO3qRt20ka7RjNkGa7ctVU0hBD-TdRGbB9Z3LElfCzbq2bPxMz8Hc7ouyZ6bmXdAFrgwA5s55P6zrbfnVea1AUCPC1NkQ8ABJt6HeE6sVdf9YX1EleGX02isSMRjd91SHeksQbz9wMz0-sqlS5Lb0sYLcyDte8T5qW8t1OH3-ydCY9FsM0QyIfl8TXtQ3y4NVXnJ52uJiwAxn3S-_1TOE6D8g8JiWSW8BKblz9T_nkClCXnskRqb7L9_TwaLbIa53qW2a04I_Kj0bsKVmHnx32h6PxakmWHkleLIBs4ZQp1XaqBad_7-vhrUPdC4Mv0H2P-QNuxVlcjaPmTaBx_HWX-ewJXt3cyFK9m_xPJ3OFkz3z97UsaZnOz8VdvBD5G1Wqvzd8gEd3ZdAEwjqVG2l47oxaF3UjIzUQL7W9Gvm0f42vvW4M6rhHElyPN1VUOoFWnq-4Z4YQrft5cpzXazSShNGHXIePoLheACIykHgREhiQHT22XrhFFeXuVkRA7B9OOZnU13xi9dGBKugN6bAXh8codgd6JpUMcJ5dk2DpFyJ37; BureauOfReclamation_QaC2=SAZTkXXvjR-a1TLRHYJspixLxvX4lIHEiLwcjTzeqMeVbfIkzQDHq6a4SCqPJ_xF5fYw5ctehUfFkPeYXN1l502g__rg6nfcJmMAsrsH2dQSmhIX007ka2ObmPFVXdu5uzX5Ak515PPfh6zfXS9HXXy7GLQoYzB6ULU2deSDed_xno2eBeenCoZ5cS3ZEIYvQjh-57NTRnfj5hWf5KF_IBJK4sMPeLsBG1kxa4IZqx_wGns3JqdzWdpDp7JYC_akvyrww_smm8HGGVnw; _gat_gtag_UA_134855355_1=1
Host: bor.qa.projectfirma.com
Referer: https://bor.qa.projectfirma.com/Project/Index
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
origin: https://bor.qa.projectfirma.com
x-requested-with: XMLHttpRequest
sec-fetch-mode: cors
sec-fetch-site: same-origin

System.NullReferenceException: ReclamationAgreementProject needs to implement IAuditableEntity
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject, String message) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\LtInfo.Common\DesignByContract\Check.cs:line 123
   at ProjectFirmaModels.Models.AuditLog.GetIAuditableEntityFromEntity(Object entity, String tableName) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\AuditLog.cs:line 368
   at ProjectFirmaModels.Models.AuditLog.CreateAuditLogEntryForDeleted(ObjectContext objectContext, DbEntityEntry dbEntry, String tableName, Person person, DateTime changeDate, AuditLogEventType auditLogEventType, Int32 tenantID) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\AuditLog.cs:line 153
   at ProjectFirmaModels.Models.AuditLog.GetAuditLogRecordsForModifiedOrDeleted(DbEntityEntry dbEntry, Person person, ObjectContext objectContext, Int32 tenantID) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\AuditLog.cs:line 95
   at ProjectFirmaModels.Models.DatabaseEntities.SaveChangesImpl(Person person, Tenant tenant, TransactionScope scope) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\DatabaseEntities.cs:line 76
   at ProjectFirmaModels.Models.DatabaseEntities.SaveChanges(Person userPerson) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\DatabaseEntities.cs:line 42
   at ProjectFirmaModels.Models.DatabaseEntities.SaveChanges() in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirmaModels\Models\DatabaseEntities.cs:line 48
   at ProjectFirma.Web.Common.SitkaController.OnActionExecuted(ActionExecutedContext filterContext) in C:\Sitka\Alevin\Temp\build\AlevinTrunk\Alevin\Source\ProjectFirma.Web\Common\SitkaController.cs:line 158
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)